#ifndef AUDIO_CLIP_01_H
#define AUDIO_CLIP_01_H

#include <cstdint>

// Auto-generated by wav2cpp — do not edit

extern const int16_t CLIP_01_SAMPLES[];
constexpr uint32_t CLIP_01_SAMPLE_RATE = 96000;
constexpr uint32_t CLIP_01_NUM_SAMPLES = 210177;
constexpr uint8_t  CLIP_01_NUM_CHANNELS = 1;

#endif // AUDIO_CLIP_01_H
