#ifndef AUDIO_CLIP_03_H
#define AUDIO_CLIP_03_H

#include <cstdint>

// Auto-generated by wav2cpp — do not edit

extern const int16_t CLIP_03_SAMPLES[];
constexpr uint32_t CLIP_03_SAMPLE_RATE = 44100;
constexpr uint32_t CLIP_03_NUM_SAMPLES = 57647;
constexpr uint8_t  CLIP_03_NUM_CHANNELS = 1;

#endif // AUDIO_CLIP_03_H
