#ifndef AUDIO_CLIP_06_H
#define AUDIO_CLIP_06_H

#include <cstdint>

// Auto-generated by wav2cpp — do not edit

extern const int16_t CLIP_06_SAMPLES[];
constexpr uint32_t CLIP_06_SAMPLE_RATE = 48000;
constexpr uint32_t CLIP_06_NUM_SAMPLES = 59904;
constexpr uint8_t  CLIP_06_NUM_CHANNELS = 1;

#endif // AUDIO_CLIP_06_H
