#ifndef AUDIO_CLIP_05_H
#define AUDIO_CLIP_05_H

#include <cstdint>

// Auto-generated by wav2cpp — do not edit

extern const int16_t CLIP_05_SAMPLES[];
constexpr uint32_t CLIP_05_SAMPLE_RATE = 44100;
constexpr uint32_t CLIP_05_NUM_SAMPLES = 206755;
constexpr uint8_t  CLIP_05_NUM_CHANNELS = 1;

#endif // AUDIO_CLIP_05_H
