#ifndef AUDIO_CLIP_04_H
#define AUDIO_CLIP_04_H

#include <cstdint>

// Auto-generated by wav2cpp — do not edit

extern const int16_t CLIP_04_SAMPLES[];
constexpr uint32_t CLIP_04_SAMPLE_RATE = 44100;
constexpr uint32_t CLIP_04_NUM_SAMPLES = 122112;
constexpr uint8_t  CLIP_04_NUM_CHANNELS = 1;

#endif // AUDIO_CLIP_04_H
