#ifndef AUDIO_CLIP_02_H
#define AUDIO_CLIP_02_H

#include <cstdint>

// Auto-generated by wav2cpp — do not edit

extern const int16_t CLIP_02_SAMPLES[];
constexpr uint32_t CLIP_02_SAMPLE_RATE = 96000;
constexpr uint32_t CLIP_02_NUM_SAMPLES = 404066;
constexpr uint8_t  CLIP_02_NUM_CHANNELS = 1;

#endif // AUDIO_CLIP_02_H
