#!/usr/bin/env python3
"""
wav2cpp — Convert audio files to C++ source arrays.

Supported formats:
    .wav — uses Python stdlib only (no extra dependencies)
    .ogg — requires pydub + FFmpeg
    .mp3 — requires pydub + FFmpeg

Usage:
    python wav2cpp.py <input_file> [output_dir]

Produces a .h/.cpp pair containing the PCM samples as a const int16_t array
suitable for embedding in RP2040 firmware.
"""

import argparse
import os
import re
import struct
import sys
import wave


def sanitize_name(filename: str) -> str:
    """Convert a filename into a valid C++ identifier."""
    name = os.path.splitext(os.path.basename(filename))[0]
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if name and name[0].isdigit():
        name = "_" + name
    return name.upper()


COMPRESSED_EXTENSIONS = {".ogg", ".mp3"}


def read_compressed(path: str, mono: bool = True):
    """Read an OGG or MP3 file via pydub and return (samples, sample_rate, num_channels)."""
    try:
        from pydub import AudioSegment
    except ImportError:
        print(
            "Error: the 'pydub' package is required for OGG/MP3 files.\n"
            "Install it with: pip install pydub\n"
            "FFmpeg must also be installed and on your PATH.",
            file=sys.stderr,
        )
        sys.exit(1)

    audio = AudioSegment.from_file(path)

    # Mix to mono if requested
    if mono and audio.channels > 1:
        audio = audio.set_channels(1)

    # Convert to 16-bit
    audio = audio.set_sample_width(2)

    sample_rate = audio.frame_rate
    num_channels = audio.channels
    raw = audio.raw_data

    fmt = f"<{len(raw) // 2}h"
    samples = list(struct.unpack(fmt, raw))

    return samples, sample_rate, num_channels


def read_wav(path: str, mono: bool = True):
    """Read a WAV file and return (samples, sample_rate, num_channels).

    samples is a list of int16 values.  If mono=True and the source is
    stereo, channels are averaged down to mono.
    """
    with wave.open(path, "rb") as wf:
        n_channels = wf.getnchannels()
        sample_width = wf.getsampwidth()
        sample_rate = wf.getframerate()
        n_frames = wf.getnframes()
        raw = wf.readframes(n_frames)

    # Convert to 16-bit signed samples
    if sample_width == 1:
        # 8-bit unsigned → 16-bit signed
        samples = [(b - 128) * 256 for b in raw]
        samples_per_frame = n_channels
    elif sample_width == 2:
        fmt = f"<{len(raw) // 2}h"
        samples = list(struct.unpack(fmt, raw))
        samples_per_frame = n_channels
    elif sample_width == 3:
        # 24-bit signed → 16-bit signed
        samples = []
        for i in range(0, len(raw), 3):
            val = int.from_bytes(raw[i : i + 3], byteorder="little", signed=True)
            samples.append(val >> 8)
        samples_per_frame = n_channels
    elif sample_width == 4:
        # 32-bit signed → 16-bit signed
        fmt = f"<{len(raw) // 4}i"
        samples = [s >> 16 for s in struct.unpack(fmt, raw)]
        samples_per_frame = n_channels
    else:
        raise ValueError(f"Unsupported sample width: {sample_width}")

    # Mix to mono if requested
    if mono and n_channels > 1:
        mono_samples = []
        for i in range(0, len(samples), n_channels):
            frame = samples[i : i + n_channels]
            avg = sum(frame) // n_channels
            # Clamp to int16 range
            avg = max(-32768, min(32767, avg))
            mono_samples.append(avg)
        samples = mono_samples
        out_channels = 1
    else:
        out_channels = n_channels

    return samples, sample_rate, out_channels


def write_cpp(samples, sample_rate, num_channels, name, output_dir):
    """Write .h and .cpp files for the audio data."""
    os.makedirs(output_dir, exist_ok=True)

    h_path = os.path.join(output_dir, f"{name.lower()}.h")
    cpp_path = os.path.join(output_dir, f"{name.lower()}.cpp")
    guard = f"AUDIO_{name}_H"

    # Header
    with open(h_path, "w", newline="\n") as f:
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"// Auto-generated by wav2cpp — do not edit\n\n")
        f.write(f"extern const int16_t {name}_SAMPLES[];\n")
        f.write(f"constexpr uint32_t {name}_SAMPLE_RATE = {sample_rate};\n")
        f.write(f"constexpr uint32_t {name}_NUM_SAMPLES = {len(samples)};\n")
        f.write(f"constexpr uint8_t  {name}_NUM_CHANNELS = {num_channels};\n\n")
        f.write(f"#endif // {guard}\n")

    # Source
    with open(cpp_path, "w", newline="\n") as f:
        f.write(f'#include "{name.lower()}.h"\n\n')
        f.write(f"// Auto-generated by wav2cpp — do not edit\n")
        f.write(f"// {len(samples)} samples, {sample_rate} Hz, "
                f"{'mono' if num_channels == 1 else 'stereo'}\n\n")
        f.write(f"const int16_t {name}_SAMPLES[] = {{\n")

        # Write 12 samples per line
        for i in range(0, len(samples), 12):
            chunk = samples[i : i + 12]
            line = ", ".join(str(s) for s in chunk)
            f.write(f"    {line},\n")

        f.write("};\n")

    return h_path, cpp_path


def main():
    parser = argparse.ArgumentParser(
        description="Convert audio files (WAV, OGG, MP3) to C++ source arrays."
    )
    parser.add_argument("input", help="Input audio file path (.wav, .ogg, .mp3)")
    parser.add_argument(
        "output_dir",
        nargs="?",
        default=None,
        help="Output directory (default: src/audio/ relative to repo root)",
    )
    parser.add_argument(
        "--stereo",
        action="store_true",
        help="Keep stereo channels (default: mix to mono)",
    )
    parser.add_argument(
        "--name",
        default=None,
        help="Override the C++ identifier name (default: derived from filename)",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"Error: file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    # Determine output directory
    if args.output_dir:
        output_dir = args.output_dir
    else:
        # Default to src/audio/ relative to the repo root (two levels up from tools/audio/)
        script_dir = os.path.dirname(os.path.abspath(__file__))
        repo_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
        output_dir = os.path.join(repo_root, "src", "audio")

    name = args.name if args.name else sanitize_name(args.input)
    mono = not args.stereo
    ext = os.path.splitext(args.input)[1].lower()

    print(f"Reading: {args.input}")
    if ext in COMPRESSED_EXTENSIONS:
        samples, sample_rate, num_channels = read_compressed(args.input, mono=mono)
    elif ext == ".wav":
        samples, sample_rate, num_channels = read_wav(args.input, mono=mono)
    else:
        print(f"Error: unsupported file format '{ext}'. Use .wav, .ogg, or .mp3.",
              file=sys.stderr)
        sys.exit(1)
    print(f"  {len(samples)} samples, {sample_rate} Hz, "
          f"{'mono' if num_channels == 1 else 'stereo'}")

    h_path, cpp_path = write_cpp(samples, sample_rate, num_channels, name, output_dir)
    print(f"Written: {h_path}")
    print(f"Written: {cpp_path}")

    # Size estimate
    size_kb = (len(samples) * 2) / 1024
    print(f"Approx flash usage: {size_kb:.1f} KB")


if __name__ == "__main__":
    main()
